# Generated by Django 5.1.1 on 2024-10-31 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('ini-cog', 'Engrenagem'), ('ini-stats-up', 'Gráficos'), ('ini-layers', 'Design'), ('ini-users', 'Usuários'), ('ini-mobile', 'Mobile'), ('ini-rocket', 'Foguete')], max_length=12, verbose_name='Icone'),
        ),
    ]
