# Generated by Django 5.1.1 on 2024-11-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_servico_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='bio',
            field=models.TextField(max_length=105, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('ini-users', 'Usuários'), ('ini-stats-up', 'Gráficos'), ('ini-layers', 'Design'), ('ini-mobile', 'Mobile'), ('ini-rocket', 'Foguete'), ('ini-cog', 'Engrenagem')], max_length=12, verbose_name='Icone'),
        ),
    ]
